apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: rtvms
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka.ads.svc.cluster.local
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.ads.svc.cluster.local:2181
            - name: KAFKA_BROKER_ID_COMMAND
              value: "hostname | awk -F'-' '{print $$NF}'"
