apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: rtvms
spec:
  type: ClusterIP
  selector:
    app: zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
