version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    networks:
      - broker-kafka
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - zookeeper
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  consumer:
    container_name: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    environment:
      - KAFKA_TOPIC_NAME=beacons
      - KAFKA_ALERT_TOPIC_NAME=alerts
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
      - ALERTING_SERVICE_PORT=4000
      - ALERTING_SERVICE_SERVER=alerting
      - ALERTING_SERVICE_ENDPOINT=alert/email
      - ALERTING_SERVICE_ENDPOINT_TEST=alert/test
    ports:
      - 8001:8001
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
      - publisher
      - alerting
    networks:
      - broker-kafka

  publisher:
    container_name: publisher
    build:
      context: ./publisher
      dockerfile: Dockerfile
    environment:
      - KAFKA_TOPIC_NAME=beacons
      - KAFKA_ALERT_TOPIC_NAME=alerts
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
    ports:
      - 8000:8000
    restart: "always"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - broker-kafka
    labels:
      kompose.service.type: LoadBalancer
  alerting:
    container_name: alert-service
    build:
      context: ../alerting-service
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: "always"
    networks:
      - broker-kafka


networks:
  broker-kafka:
    driver: bridge
