apiVersion: v1
kind: Service
metadata:
  name: alerting-service
  namespace: rtvms
spec:
  selector:
    app: alertingService
  ports:
    - name: http
      port: 8004
      targetPort: 4000
  type: LoadBalancer
  externalTrafficPolicy: Local
